<a href="https://colab.research.google.com/github/RorisangSitoboli/Optimization/blob/main/DistanceCalculatorOptimisation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import required libraries
import math
import numpy as np
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import sklearn

In [2]:
# Example 2D coordinates
p = [8, 5]
q = [3, 4]

In [3]:
''' Use the Math library for quick and easy Eucliden distance calculation.
Available only in Python 3.8 and up'''

#print (math.dist(p, q))

' Use the Math library for quick and easy Eucliden distance calculation.\nAvailable only in Python 3.8 and up'

In [4]:
# Function that uses SciPy to calculate the shortest distance from user defined origin/point.
from scipy.spatial.distance import cdist
def shortest_distance(x, y):
    origin_point = np.array([[x,y]])
    target_points = np.array([[1,0], [2,3], [4,3]])
    d = cdist(origin_point, target_points)
    return d

In [5]:
# Shortest distance from origin, (0. 0).
shortest_distance(0,0)

array([[1.        , 3.60555128, 5.        ]])

In [6]:
a = np.array([[2., 3., 8.], [10., 4., 3.], [58., 3., 4.], [34., 2., 43.]])

In [7]:
b = np.array([[1, 0, 7], [2, 3, 6], [4, 3, 8]])

In [8]:
c = np.array([[1, 0, 0], [2, 3, 0], [4, 3, 0]])

In [9]:
#Use Nelder–Mead method in scipy.optimize (large selection of optimizers to choose from). The output is the point of shortest sum distance.
from scipy.optimize import minimize
x = [point[0] for point in a]
y = [point[1] for point in a]
z = [point[2] for point in a]

x0 = np.array([sum(x)/len(x),sum(y)/len(y), sum(z)/len(z)])
def dist_func(x0):
    return sum(((np.full(len(x),x0[0])-x)**2+(np.full(len(x),x0[1])-y)**2+(np.full(len(x),x0[2])-z)**2)**(1/2))
res = minimize(dist_func, x0, method='nelder-mead', options={'xtol': 1e-8, 'disp': True})
res.x

Optimization terminated successfully.
         Current function value: 102.856804
         Iterations: 134
         Function evaluations: 256


array([12.58942487,  3.51573846,  7.28710679])

In [10]:
from scipy.optimize import minimize
x1 = [point[0] for point in b]
y1 = [point[1] for point in b]
z1 = [point[2] for point in b]

x0 = np.array([sum(x1)/len(x1),sum(y1)/len(y1), sum(z1)/len(z1)])
def dist_func(x0):
    return sum(((np.full(len(x1),x0[0])-x1)**2+(np.full(len(x1),x0[1])-y1)**2+(np.full(len(x1),x0[2])-z1)**2)**(1/2))
res = minimize(dist_func, x0, method='nelder-mead', options={'xtol': 1e-8, 'disp': True})
res.x

Optimization terminated successfully.
         Current function value: 5.937009
         Iterations: 104
         Function evaluations: 194


array([2.27541965, 2.42907413, 6.65603688])

In [11]:
from scipy.optimize import minimize
x1 = [point[0] for point in c]
y1 = [point[1] for point in c]
z1 = [point[2] for point in c]

x0 = np.array([sum(x1)/len(x1),sum(y1)/len(y1), sum(z1)/len(z1)])
def dist_func(x0):
    return sum(((np.full(len(x1),x0[0])-x1)**2+(np.full(len(x1),x0[1])-y1)**2+(np.full(len(x1),x0[2])-z1)**2)**(1/2))
res = minimize(dist_func, x0, method='nelder-mead', options={'xtol': 1e-8, 'disp': True})
res.x

Optimization terminated successfully.
         Current function value: 5.137344
         Iterations: 140
         Function evaluations: 262


array([2.17186440e+00, 2.77266102e+00, 1.22064816e-08])